openapi: 3.0.0
info:
  title: movement-ranking API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: Local environment
paths:
  /ranking:
    get:
      tags:
        - default
      summary: localhost:8080/ranking
      parameters:
        - name: movement
          in: query
          schema:
            type: string
          description: movement name
        - name: id
          in: query
          schema:
            type: integer
          description: movement id
          example: '1'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: Will return the ranking of the movements.
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                type: string
              example: Will return an error if the movement is not found.
