openapi: 3.0.0
info:
  title: store
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: Local environment
paths:
  /ranking:
    get:
      tags:
        - default
      summary: localhost:8080/ranking
      parameters:
        - name: movement
          in: query
          schema:
            type: string
        - name: id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
